services:

  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
  
    container_name: nldmap-dev

    working_dir: /workspace

    volumes: 
      - .:/workspace

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true

    command: sleep infinity

